name: Build assets

on:
  pull_request:
    branches:
      - 8.5.x
    paths:
      - ".github/workflows/build-assets.yml"
      - "build/**.js"
      - "build/**.json"
      - "concrete/css/build/**"
      - "concrete/js/build/**"
  push:
    branches:
      - 8.5.x
    tags-ignore:
      - "**"
    paths:
      - ".github/workflows/build-assets.yml"
      - "build/**.js"
      - "build/**.json"
      - "concrete/css/build/**"
      - "concrete/js/build/**"

jobs:
  build:
    name: Build CSS and JavaScript assets
    runs-on: ubuntu-latest
    env:
      PUSH_CHANGES: n
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install Grunt
        run: npm -g install grunt
      - name: Install dependencies
        run: cd build && npm ci && cd ..
      - name: Build CSS assets
        run: cd build && grunt css:release && cd ..
      - name: Build JavaScript assets
        run: cd build && grunt js:release && cd ..
      - name: Check JS assets
        if: github.event_name == 'pull_request'
        run: cd build && grunt js:check && cd ..
      - name: Check changes
        if: >
          github.event_name == 'push'
          && github.ref == 'refs/heads/8.5.x'
          && github.repository == 'concrete5/concrete5'
          && !startsWith(github.event.head_commit.message, '[skip ci]')
        run: |
          PUSH_CHANGES=n
          cd concrete/css
          if test -n "$(git status --porcelain .)"; then
            echo '- changes detected in CSS assets'
            git add --all .
            PUSH_CHANGES=y
          else
            echo '- no changes in CSS assets'
          fi
          cd ../..
          cd concrete/js
          if test -n "$(git status --porcelain .)"; then
            echo '- changes detected in JS assets'
            git add --all .
            PUSH_CHANGES=y
          else
            echo '- no changes in JS assets'
          fi
          cd ../..
          printf 'PUSH_CHANGES=%s\n' "$PUSH_CHANGES" >> "$GITHUB_ENV"
      - name: Commit and push
        if: env.PUSH_CHANGES == 'y'
        run: |
          printf 'Configuring git... '
          git config --local user.name 'concrete5 bot'
          git config --local user.email 'concrete5-bot@concrete5.org'
          echo 'done.'
          echo 'Committing changes'
          git commit -m '[skip ci] Automatic assets rebuilding'
          echo 'Pushing'
          git push
